# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'PopupAdMob' do

platform :ios, ‘8.0’
pod 'Google-Mobile-Ads-SDK', '~> 7.0'

end

